### ISSUE TITLE
VroomJSNative error

### ISSUE THREAD

**Issue by trevorgk** [pauldotknopf/react-dot-net#11]
Hello,

I am receiving the error pasted below when I run the command: `dnx ef database update`. The file is in the location specified in the exception and I have given full permissions to all users to test if this was the problem.

I'm running 32 bit windows 7, is this likely to be part of the problem?

PS C:\wwwroot\sites\react-aspnet-boilerplate\src\React> dnx ef database update
System.Exception: Couldn't load native assembly at C:\Users\lukas\AppData\Local\Temp\VroomJs.1.0.1.0\x86\VroomJsNative.dll
   at VroomJs.AssemblyLoader.LoadDll(String dllName, String architecture)
   at VroomJs.AssemblyLoader.EnsureLoaded()
   at React.Startup..ctor(IHostingEnvironment env) in C:\wwwroot\sites\react-aspnet-boilerplate\src\React\Startup.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Obj
ect[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)

   at Microsoft.Data.Entity.Design.Internal.StartupInvoker.Invoke(Type type, String[] methodNames, IServiceCollection services)
   at Microsoft.Data.Entity.Design.Internal.StartupInvoker.ConfigureServices()
   at Microsoft.Data.Entity.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAs
semblyName, String environment)
   at Microsoft.Data.Entity.Design.MigrationsOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupA
ssemblyName, String environment, String projectDir, String rootNamespace)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass4_1.<.ctor>b__4()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass7_0.<UpdateDatabase>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Couldn't load native assembly at C:\Users\lukas\AppData\Local\Temp\VroomJs.1.0.1.0\x86\VroomJsNative.dll

**Comment by pauldotknopf** [comment]
Can you run `depends` on that .dll and make sure you have all the dependencies installed? I believe you need VC2013 x86 redistributables.

**Comment by pauldotknopf** [comment]
Any update on this?

**Comment by neilyoung** [comment]
Couldn't load native assembly at C:\Users....\Local\Temp\VroomJs.
1.0.1.0\x86\VroomJsNative.dll

Same here. It says it is missing api-ms-win-core-rtlsupport-l1-2.0.dll

Never had any problem with dnx ef database update before

EDIT: Installed VS2015 and VS2013 redistributable packages. Same problem. The dnx ef database update passes, if I'm removing references to VroomJs from Startup.cs, but then it crashes at startup

EDIT2: Your template shouldn't rely on DLLs only available on Windows 8 or higher

**Comment by pauldotknopf** [comment]
@neilyoung, I am working on this issue as we speak. We are probally going to move away from using V8, and instead, use `node.exe` directly (either stdin/stdout  or HTTP).

**Comment by neilyoung** [comment]
Thanks for letting me know. Staying tuned :)

**Comment by pauldotknopf** [comment]
I have finished on one branch, [`empty-template`](https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/empty-template). Can you give it a shot?

I should have `master` done in a few days. I'll ping you when it is done.

**Comment by pauldotknopf** [comment]
`master` (and all other branches) are now RC2, and use a different javascript backend. You shouldn't have this issue anymore.

**Comment by neilyoung** [comment]
Yes, works. Thanks for fixing it. Tried to rename modules to .jsx in order  to get rid of the error markers in VS, to no avail. Still trying to understand your voodoo :)

**Comment by pauldotknopf** [comment]
@neilyoung, That should all be webpack stuff. Is webpack giving you errors?
