### ISSUE TITLE
Core1 RC2 and route rendering question

### ISSUE THREAD

**Issue by dwightjack** [pauldotknopf/react-dot-net#12]
Hi,

I'm trying to run this project on Mac OSX with the latest Core1 RC2, but the project cannot run. I even managed to install RC1, which runs fine until the database cli command which fails with the following error:

```
The current runtime target framework is not compatible with 'React'.
Current runtime target framework: 'DNXCore,Version=v5.0 (dnxcore50)'
 Version:      1.0.0-rc1-16609
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64
```

Looking at the code I understand that routes are defined both clientside in `routes.js` and serverside in .net controllers. If that's correct, I could have a duplicate route mapping in the server and client codebase which seems not that easy to maintain in a big app.

Thanks in advance.

**Comment by pauldotknopf** [comment]
There is a dependency that I still need to update, [vroomjs-core](https://github.com/pauldotknopf/vroomjs-core), before we fully support .NET Core. I am waiting for RTM before I do, because there is so many things changing right now in .NET Core. For now, only CLR is supported.

As for your mention on managing client-side routing and server-side routing, there are multiple approaches you can take.

You can either have a large catch-all MVC handler that sends the request to the ViewEngine. However, the whole point of supporting server-side rendering is so that we can hydrate the redux store, per request. So, you will need a separate MVC handler that has a single responsibility of loading the default redux store for that page only. This would only be for one a search engine visits your page, or a user. This is why you will need to handle multiple routes. One for client-side navigation, and another one for a fresh boot.

**Comment by pauldotknopf** [comment]
Update: I just finished refactoring `JavaScriptViewEngine` a little. It is updated for RC2, and also fully supports .NET Core (Linux/Mac/Windows).

This week, I will have `react-aspnet-boilerplate` migrated to RC2 with support for the new `JavaScriptViewEngine`. I will ping you when it is done.

**Comment by dwightjack** [comment]
Thank you very much!

**Comment by pauldotknopf** [comment]
I have finished on one branch, [`empty-template`](https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/empty-template). Can you give it a shot?

I should have `master` done in a few days. I'll ping you when it is done.

**Comment by pauldotknopf** [comment]
PING: all branches are RC2, and fully support Linux/Mac/Windows.

**Comment by dwightjack** [comment]
Thanks! We will give it a try in the next days.

**Comment by dwightjack** [comment]
I confirm the project works as expected!

I'm running it on Mac OSX. The only working I'm getting is when i run `dotnet ef database update`:

```
System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
```

Thank you very much!

**Comment by pauldotknopf** [comment]
@dwightjack, Ya, the database stuff in the template probally isn't cross-platform, since it is using `localdb`. You probally need to just setup a Sql Server on a Windows machine, and update your `appsettings.json` to point to it via a traditional tcp-based connection string.
