### ISSUE TITLE
get an error while creating empty template

### ISSUE THREAD

**Issue by akshaymittal143** [pauldotknopf/react-dot-net#49]
Error: write after end
    at writeAfterEnd (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:288:12)
    at Transform.Writable.write (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:332:20)
    at DestroyableTransform.ondata (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:189:13)
    at addChunk (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform._transform (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/mem-fs-editor/lib/actions/commit.js:34:12)
    at DestroyableTransform.Transform._read (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_transform.js:184:10)
Emitted 'error' event at:
    at Transform.onerror (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:189:13)
    at writeAfterEnd (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:290:10)
    at Transform.Writable.write (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:332:20)
    [... lines matching original stack trace ...]
    at DestroyableTransform.Transform.push (/Users/amittal/.nvm/versions/node/v10.15.3/lib/node_modules/generator-react-aspnet-boilerplate/node_modules/readable-stream/lib/_stream_transform.js:148:32)

**Comment by bwdmonkey** [comment]
@akshaymittal143 Were you able to resolve this issue? I am facing the same issue.

**Comment by fredericdasilva** [comment]
Hello, same issue for me. Any fix for this issue ?
